source 'https://rubygems.org'
	ruby '2.5.1'
		gem 'dotenv'
		gem 'rspec'
		gem 'twitter'
		gem 'rubocop',' ~> 0.57.2'
		gem 'pry'
		gem 'nokogiri'
		gem 'launchy'

		gem 'csv'
		gem 'sinatra'
		gem 'shotgun'